# CI.yaml --- Check Puppet module

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check:
    name: Puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-latest
    container: puppet/pdk:latest

    strategy:
      fail-fast: false
      matrix:
        puppet_version: [7, 8]

    steps:
      - name: Install build-essential
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get --yes update
          apt-get --yes install build-essential

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run pdk validate
        run: pdk validate --format=text --puppet-version ${{ matrix.puppet_version }}

      - name: Run pdk test unit
        run: pdk test unit --format=text --puppet-version ${{ matrix.puppet_version }}
